# Generated by Django 4.0.6 on 2022-09-26 03:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntregaFinal', '0003_locales_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='xx'),
            preserve_default=False,
        ),
    ]
